### ISSUE TITLE
Undefined symbol reference

### ISSUE THREAD

**Issue by Torrekie** [Pomelo-Emu/Pomelo#2]
```
  "termination" : {"code":4,"flags":518,"namespace":"DYLD","indicator":"Symbol missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Symbol not found: _$s10Foundation12NotificationV36_unconditionallyBridgeFromObjectiveCyACSo14NSNotificationCSgFZ","Referenced from: \/private\/var\/containers\/Bundle\/Application\/A7E81910-E4D4-436E-8781-2318AAB6EFE6\/Pomelo.app\/Pomelo.debug.dylib","Expected in: \/System\/Library\/Frameworks\/Foundation.framework\/Foundation"]},
```

Please compile with an older iPhoneOS.sdk or make it __builtin_available

**Comment by stossy11** [comment]
ill look into lowering the iOS SDK.

**Comment by Torrekie** [comment]
another thing, can you downgrade the xcodeproj format to Xcode 11 compatible for me to attempt to backport to iOS 14?

**Comment by stossy11** [comment]
> another thing, can you downgrade the xcodeproj format to Xcode 11 compatible for me to attempt to backport to iOS 14?

I could backport myself to iOS 14, but as iOS 16 doesn't work I don't think iOS 14 will work so it would be a waste of time.
